# Generated by Django 4.1.7 on 2023-05-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproHome', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='boooking_data',
            new_name='booking_data',
        ),
    ]
