# Generated by Django 4.1.7 on 2023-05-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproHome', '0005_rename_boooking_data_booking_booking_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_data',
            new_name='booking_date',
        ),
    ]
